/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ZULFA
 */

import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class DataKerusakan extends javax.swing.JFrame {

    /**
     * Creates new form DataKerusakan
     */
    
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    Connection cn = database.kerusakandb.configDB();
    Vector originalTableModel;
    
    public DataKerusakan() {
        initComponents();
        showDataKerusakan();
        setColumnWidth();
        originalTableModel = (Vector) ((DefaultTableModel) tabelDataKerusakan.getModel()).getDataVector().clone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDataKerusakan = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtKodeKerusakan = new javax.swing.JTextField();
        txtKerusakan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSolusiKerusakan = new javax.swing.JTextArea();
        txtCariDataTable = new javax.swing.JTextField();
        btnCariData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 242, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(237, 235, 230));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 58, 58));
        jLabel1.setText(" Kerusakan");

        btnKembali.setBackground(new java.awt.Color(237, 235, 230));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(55, 58, 58));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 58, 58));
        jLabel2.setText("Kode Kerusakan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 58, 58));
        jLabel3.setText("Nama Kerusakan");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 58, 58));
        jLabel4.setText("Solusi Kerusakan");

        tabelDataKerusakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataKerusakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataKerusakanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelDataKerusakan);

        btnSimpan.setBackground(new java.awt.Color(88, 158, 85));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(237, 235, 230));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-20.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(213, 142, 29));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(237, 235, 230));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-20 (1).png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(55, 58, 58));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(237, 235, 230));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset-20.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(244, 67, 54));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(237, 235, 230));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-remove-20.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtAreaSolusiKerusakan.setColumns(20);
        txtAreaSolusiKerusakan.setRows(5);
        jScrollPane1.setViewportView(txtAreaSolusiKerusakan);

        btnCariData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCariData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe.png"))); // NOI18N
        btnCariData.setText("Cari");
        btnCariData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCariData.setFocusable(false);
        btnCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnKembali)
                .addGap(444, 444, 444)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHapus)
                        .addGap(77, 77, 77)
                        .addComponent(btnReset)
                        .addGap(72, 72, 72)
                        .addComponent(btnEdit)
                        .addGap(91, 91, 91)
                        .addComponent(btnSimpan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(txtKerusakan)
                            .addComponent(txtKodeKerusakan)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCariDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtKodeKerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnReset)
                    .addComponent(btnHapus))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      public void setColumnWidth(){
        TableColumnModel columnModel = tabelDataKerusakan.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(0).setMaxWidth(30);
        columnModel.getColumn(0).setMinWidth(30);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(1).setMaxWidth(120);
        columnModel.getColumn(1).setMinWidth(120);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(2).setMaxWidth(150);
        columnModel.getColumn(2).setMinWidth(150);
    }
    
    private void showDataKerusakan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Kode Kerusakan");
        model.addColumn("Kerusakan");
        model.addColumn("Solusi Kerusakan");
        tabelDataKerusakan.setModel(model);
        try {
            st = cn.createStatement();
            String sql = "SELECT * FROM kerusakan";
            rs = st.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id") , rs.getString("kode_kerusakan") , rs.getString("nama_kerusakan") , rs.getString("solusi_kerusakan")});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA");
        }
        
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtKodeKerusakan.setText("");
        txtKerusakan.setText("");
        txtAreaSolusiKerusakan.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String kodeKerusakan = txtKodeKerusakan.getText();
        String kerusakan = txtKerusakan.getText();
        String solusiKerusakan = txtAreaSolusiKerusakan.getText();
        
        if(kerusakan.equals("") || kodeKerusakan.equals("") || solusiKerusakan.equals("")){
            JOptionPane.showMessageDialog(null, "DATA TIDAK BOLEH KOSONG", "PERINGATAN" , JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                String sql = "INSERT INTO kerusakan VALUES ( id,'" + kodeKerusakan + "', '" + kerusakan + "' , '" + solusiKerusakan + "')";
                st = cn.createStatement();
                st.executeUpdate(sql);
                reset();
                showDataKerusakan();
                setColumnWidth();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DI SIMPAN");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DI SIMPAN");
                reset();
            }
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tabelDataKerusakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataKerusakanMouseClicked
        // TODO add your handling code here:
        tabelDataKerusakan.getValueAt(tabelDataKerusakan.getSelectedRow(),0);
        txtKodeKerusakan.setText(tabelDataKerusakan.getValueAt(tabelDataKerusakan.getSelectedRow(),1).toString());
        txtKerusakan.setText(tabelDataKerusakan.getValueAt(tabelDataKerusakan.getSelectedRow(),2).toString());
        txtAreaSolusiKerusakan.setText(tabelDataKerusakan.getValueAt(tabelDataKerusakan.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelDataKerusakanMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin Data mau di hapus?");
        
        if(confirm == 0){
        try {
            String id = tabelDataKerusakan.getValueAt(tabelDataKerusakan.getSelectedRow(),0).toString();
            String sql = "DELETE FROM kerusakan WHERE id = '" + id + "'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
            reset();
            showDataKerusakan();
            setColumnWidth();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String id = tabelDataKerusakan.getValueAt(tabelDataKerusakan.getSelectedRow(),0).toString();
        String kodeKerusakan = txtKodeKerusakan.getText();
        String kerusakan = txtKerusakan.getText();
        String solusiKerusakan = txtAreaSolusiKerusakan.getText();
        try {
         st = cn.createStatement();
         String sql = "UPDATE kerusakan SET kode_kerusakan = '" + kodeKerusakan + "',  nama_kerusakan = '" + kerusakan + "', solusi_kerusakan = '" + solusiKerusakan + "' WHERE id = '" + id + "'";
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH");
         showDataKerusakan();
         setColumnWidth();
         reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new HalamanAdmin().show();
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tampilDataTabel(String cariData){
        DefaultTableModel model =  (DefaultTableModel) tabelDataKerusakan.getModel();
        model.setRowCount(0);
        for(Object rows : originalTableModel ){
        Vector rowVector = (Vector) rows;
           for(Object column : rowVector){
             if(column.toString().contains(cariData)){
                   model.addRow(rowVector);
                    break;
                }
            }
        }
    }
    
    private void btnCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDataActionPerformed
        // TODO add your handling code here:
        String cariDataTabel = txtCariDataTable.getText();
        tampilDataTabel(cariDataTabel);
    }//GEN-LAST:event_btnCariDataActionPerformed

    private void reset(){
        txtKodeKerusakan.setText("");
        txtKerusakan.setText("");
        txtAreaSolusiKerusakan.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKerusakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKerusakan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariData;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelDataKerusakan;
    private javax.swing.JTextArea txtAreaSolusiKerusakan;
    private javax.swing.JTextField txtCariDataTable;
    private javax.swing.JTextField txtKerusakan;
    private javax.swing.JTextField txtKodeKerusakan;
    // End of variables declaration//GEN-END:variables
}
