
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ZULFA
 */
public class DataSpareparts extends javax.swing.JFrame {

    /**
     * Creates new form DataSpareparts
     */
    
    
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    Connection cn = database.kerusakandb.configDB();
    Vector originalTableModel;
    
    ArrayList<String> totalPembelianSpareparts = new ArrayList<>();
    ArrayList<Integer> intTotalPembelianSpareparts = new ArrayList<>();
    Calendar calendar = Calendar.getInstance();
    SimpleDateFormat formatDay = new SimpleDateFormat("EEEE", new Locale("in","ID"));
    String Hari = formatDay.format(calendar.getTime());
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy" ,new Locale("id","ID"));
    String dateNow = dateFormat.format(new Date());
    
    public DataSpareparts() {
        initComponents();
        showDataSpareparts();
        setColumnWidth();
        getAllHarga(); 
        convertTotalPriceSpareparts(totalPembelianSpareparts);
        originalTableModel = (Vector) ((DefaultTableModel) tblSpareparts.getModel()).getDataVector().clone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpareparts = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNamaSpareparts = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDetailParts = new javax.swing.JTextArea();
        txtCari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnReportSpareparts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 235, 230));

        jButton1.setBackground(new java.awt.Color(237, 235, 230));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(55, 58, 58));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        jButton1.setText("Kembali");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 58, 58));
        jLabel1.setText("Nama Spareparts");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 58, 58));
        jLabel2.setText("Harga");

        btnCari.setBackground(new java.awt.Color(237, 235, 230));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(55, 58, 58));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblSpareparts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSpareparts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSparepartsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSpareparts);

        btnHapus.setBackground(new java.awt.Color(244, 67, 54));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(237, 235, 230));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-remove-20.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(55, 58, 58));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(237, 235, 230));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset-20.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(213, 142, 29));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(237, 235, 230));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-20 (1).png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(88, 158, 85));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(237, 235, 230));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-20.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 58, 58));
        jLabel3.setText("Detail parts");

        txtAreaDetailParts.setColumns(20);
        txtAreaDetailParts.setRows(5);
        jScrollPane3.setViewportView(txtAreaDetailParts);

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 58, 58));
        jLabel4.setText("Spareparts");

        btnReportSpareparts.setBackground(new java.awt.Color(237, 235, 230));
        btnReportSpareparts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportSpareparts.setForeground(new java.awt.Color(55, 58, 58));
        btnReportSpareparts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btnReportSpareparts.setText("Report Spareparts");
        btnReportSpareparts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportSpareparts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportSparepartsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(435, 435, 435))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportSpareparts, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(158, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                            .addComponent(btnCari))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                                            .addComponent(txtNamaSpareparts))))))))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaSpareparts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnReset)
                    .addComponent(btnHapus)
                    .addComponent(btnReportSpareparts))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setColumnWidth(){
        TableColumnModel columnModel = tblSpareparts.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(0).setMaxWidth(30);
        columnModel.getColumn(0).setMinWidth(30);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(1).setMaxWidth(150);
        columnModel.getColumn(1).setMinWidth(150);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(2).setMaxWidth(100);
        columnModel.getColumn(2).setMinWidth(100);
    } 
    
    private void showDataSpareparts(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nama Spareparts");
        model.addColumn("Harga");
        model.addColumn("Detail Spareparts");
        model.addColumn("Tanggal");
        tblSpareparts.setModel(model);
        try {
            st = cn.createStatement();
            String sql = "SELECT * FROM spareparts";
            rs = st.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id") , rs.getString("nama_spareparts") , rs.getString("harga") , rs.getString("detail_parts"), rs.getString("tanggal")});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA");
        }
    }
    
     private void reset(){
        txtNamaSpareparts.setText("");
        txtHarga.setText("");
        txtAreaDetailParts.setText("");
    }
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(null, "Yakin Data mau di hapus?");

        if(confirm == 0){
            try {
                String id = tblSpareparts.getValueAt(tblSpareparts.getSelectedRow(),0).toString();
                String sql = "DELETE FROM spareparts WHERE id = '" + id + "'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
                showDataSpareparts();
                setColumnWidth();
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtNamaSpareparts.setText("");
        txtHarga.setText("");
        txtAreaDetailParts.setText("");
        txtCari.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String id = tblSpareparts.getValueAt(tblSpareparts.getSelectedRow(),0).toString();
        String namaSpareparts = txtNamaSpareparts.getText();
        String harga = txtHarga.getText();
        String detailParts = txtAreaDetailParts.getText();
        try {
            st = cn.createStatement();
            String sql = "UPDATE spareparts SET nama_spareparts = '" + namaSpareparts + "', harga = '" + harga + "', detail_parts = '" + detailParts + "' WHERE id = '" + id + "'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH");
            showDataSpareparts();
            setColumnWidth();
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String namaSpareparts = txtNamaSpareparts.getText();
        String harga = txtHarga.getText();
        String detailParts = txtAreaDetailParts.getText();
        LocalDate today = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy", new Locale("id,ID"));
        String formateDate = today.format(formatter);
        
        if(harga.equals("") || namaSpareparts.equals("")){
            JOptionPane.showMessageDialog(null, "DATA TIDAK BOLEH KOSONG", "PERINGATAN" , JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                String sql = "INSERT INTO spareparts VALUES ( id,'" + namaSpareparts + "', '" + harga + "', '" + detailParts + "', '" + formateDate + "')";
                st = cn.createStatement();
                st.executeUpdate(sql);
                showDataSpareparts();
                setColumnWidth();
                reset();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DI SIMPAN");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DI SIMPAN");
                reset();
            }
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblSparepartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSparepartsMouseClicked
        // TODO add your handling code here:
        tblSpareparts.getValueAt(tblSpareparts.getSelectedRow(), 0);
        txtNamaSpareparts.setText(tblSpareparts.getValueAt(tblSpareparts.getSelectedRow(),1).toString());
        txtHarga.setText(tblSpareparts.getValueAt(tblSpareparts.getSelectedRow(),2).toString());
        txtAreaDetailParts.setText(tblSpareparts.getValueAt(tblSpareparts.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tblSparepartsMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String cariDataTabel = txtCari.getText();
        tampilDataTabel(cariDataTabel);
    }//GEN-LAST:event_btnCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HalamanAdmin().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void getAllHarga(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT harga FROM spareparts");
            while(rs.next()){
                String totalPembayaranSpareparts = rs.getString("harga");
                totalPembelianSpareparts.add(totalPembayaranSpareparts);
            }
            for(int i = 0; i < totalPembelianSpareparts.size(); i++){
                String word = totalPembelianSpareparts.get(i);
                StringBuilder modifiedWord = new StringBuilder();
                for(int j = 0; j < word.length(); j++){
                    char letter = word.charAt(j);
                  if(!isVowel(letter)){
                      modifiedWord.append(letter);
                  }
                }
                totalPembelianSpareparts.set(i, modifiedWord.toString());
            }
        } catch (Exception e) {
        }
    }
     
   public static boolean isVowel(char letter) {
        letter = Character.toLowerCase(letter);
        return letter == 'r' || letter == 'p' || letter == '.';
    }
   
   public void convertTotalPriceSpareparts (ArrayList<String> values){
       for(String value : values){
           String valueStr = value.trim();
           int valueInt = Integer.parseInt(String.valueOf(valueStr));
           intTotalPembelianSpareparts.add(valueInt);
       }
   }
 
    private void btnReportSparepartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportSparepartsActionPerformed
        // TODO add your handling code here:
        try {
          
          int costSpareparts = 0;
          for(Integer value : intTotalPembelianSpareparts){
              costSpareparts += value;
          }
          String totalCostSpareparts = String.valueOf("Rp " + costSpareparts);
          JasperReport jasperReport = JasperCompileManager.compileReport("C:\\Users\\ZULFA\\Documents\\NetBeansProjects\\taSistemPakarKerusakan\\src\\reportDataPemasukanSpareparts.jrxml");
          Map<String, Object> parameters = new HashMap<>();
          parameters.put("totalCostSpareparts", totalCostSpareparts);
          parameters.put("tanggal",Hari +", "+ dateNow);
          JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, cn);
          JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnReportSparepartsActionPerformed

     private void tampilDataTabel(String cariData){
        DefaultTableModel model =  (DefaultTableModel) tblSpareparts.getModel();
        model.setRowCount(0);
        for(Object rows : originalTableModel ){
            Vector rowVector = (Vector) rows;
            for(Object column : rowVector){
                if(column.toString().contains(cariData)){
                    model.addRow(rowVector);
                    break;
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSpareparts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReportSpareparts;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblSpareparts;
    private javax.swing.JTextArea txtAreaDetailParts;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaSpareparts;
    // End of variables declaration//GEN-END:variables
}
