/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ZULFA
 */
public class HalamanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public HalamanAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBasisPengetahuan2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnKerusakan = new javax.swing.JButton();
        btnCiriKerusakan = new javax.swing.JButton();
        btnBasisPengetahuan = new javax.swing.JButton();
        imgKerusakan = new javax.swing.JLabel();
        imgBasisPengetahuan = new javax.swing.JLabel();
        btnAturan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRekapDiagnosa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnSpareparts = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        btnBasisPengetahuan2.setBackground(new java.awt.Color(237, 235, 230));
        btnBasisPengetahuan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBasisPengetahuan2.setForeground(new java.awt.Color(55, 58, 58));
        btnBasisPengetahuan2.setText("Riwayat Konsultasi");
        btnBasisPengetahuan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBasisPengetahuan2.setFocusable(false);
        btnBasisPengetahuan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasisPengetahuan2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1240, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(237, 235, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 58, 58));
        jLabel2.setText("Sistem Pakar Diagnosa Kerusakan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 58, 58));
        jLabel3.setText("Motor Vespa 2 Tak");

        btnKerusakan.setBackground(new java.awt.Color(237, 235, 230));
        btnKerusakan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKerusakan.setForeground(new java.awt.Color(55, 58, 58));
        btnKerusakan.setText("Kerusakan");
        btnKerusakan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKerusakan.setFocusable(false);
        btnKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKerusakanActionPerformed(evt);
            }
        });

        btnCiriKerusakan.setBackground(new java.awt.Color(237, 235, 230));
        btnCiriKerusakan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCiriKerusakan.setForeground(new java.awt.Color(55, 58, 58));
        btnCiriKerusakan.setText("Gejala Kerusakan");
        btnCiriKerusakan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCiriKerusakan.setFocusable(false);
        btnCiriKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiriKerusakanActionPerformed(evt);
            }
        });

        btnBasisPengetahuan.setBackground(new java.awt.Color(237, 235, 230));
        btnBasisPengetahuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBasisPengetahuan.setForeground(new java.awt.Color(55, 58, 58));
        btnBasisPengetahuan.setText("Basis Pengetahuan");
        btnBasisPengetahuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBasisPengetahuan.setFocusable(false);
        btnBasisPengetahuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasisPengetahuanActionPerformed(evt);
            }
        });

        imgKerusakan.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZULFA\\Documents\\NetBeansProjects\\taSistemPakarKerusakan\\src\\images\\piston (1).png")); // NOI18N
        imgKerusakan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgKerusakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgKerusakanMouseClicked(evt);
            }
        });

        imgBasisPengetahuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open-book (1).png"))); // NOI18N
        imgBasisPengetahuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgBasisPengetahuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBasisPengetahuanMouseClicked(evt);
            }
        });

        btnAturan.setBackground(new java.awt.Color(237, 235, 230));
        btnAturan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAturan.setForeground(new java.awt.Color(55, 58, 58));
        btnAturan.setText("Aturan");
        btnAturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAturan.setFocusable(false);
        btnAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturanActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(237, 235, 230));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(55, 58, 58));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/risk-study.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rule (1).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time-management.png"))); // NOI18N

        btnRekapDiagnosa.setBackground(new java.awt.Color(237, 235, 230));
        btnRekapDiagnosa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRekapDiagnosa.setForeground(new java.awt.Color(55, 58, 58));
        btnRekapDiagnosa.setText("Rekap Diagnosa");
        btnRekapDiagnosa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRekapDiagnosa.setFocusable(false);
        btnRekapDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekapDiagnosaActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spareparts.png"))); // NOI18N
        jLabel8.setToolTipText("");

        btnSpareparts.setBackground(new java.awt.Color(237, 235, 230));
        btnSpareparts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSpareparts.setForeground(new java.awt.Color(55, 58, 58));
        btnSpareparts.setText("Spareparts");
        btnSpareparts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSpareparts.setFocusable(false);
        btnSpareparts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparepartsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogout)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(98, 98, 98)
                                            .addComponent(jLabel3))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(251, 251, 251)
                                            .addComponent(btnCiriKerusakan)))
                                    .addGap(12, 12, 12)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnKerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRekapDiagnosa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBasisPengetahuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(imgBasisPengetahuan)
                                        .addGap(44, 44, 44)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAturan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSpareparts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(imgKerusakan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgKerusakan)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKerusakan)
                    .addComponent(btnCiriKerusakan))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBasisPengetahuan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBasisPengetahuan)
                    .addComponent(btnAturan))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRekapDiagnosa)
                    .addComponent(btnSpareparts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 530, 700));

        jPanel1.setBackground(new java.awt.Color(237, 235, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgKerusakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgKerusakanMouseClicked
        // TODO add your handling code here:
        new DataKerusakan().show();
        this.dispose();
    }//GEN-LAST:event_imgKerusakanMouseClicked

    private void btnKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKerusakanActionPerformed
        // TODO add your handling code here:
          new DataKerusakan().show();
        this.dispose();
    }//GEN-LAST:event_btnKerusakanActionPerformed

    private void btnCiriKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiriKerusakanActionPerformed
        // TODO add your handling code here:
        new GejalaKerusakan().show();
        this.dispose();
    }//GEN-LAST:event_btnCiriKerusakanActionPerformed

    private void imgBasisPengetahuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBasisPengetahuanMouseClicked
        // TODO add your handling code here:
        new BasisPengetahuanAdmin().show();
        this.dispose();
    }//GEN-LAST:event_imgBasisPengetahuanMouseClicked

    private void btnBasisPengetahuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasisPengetahuanActionPerformed
        // TODO add your handling code here:
        new BasisPengetahuanAdmin().show();
        this.dispose();
    }//GEN-LAST:event_btnBasisPengetahuanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new SignIn().show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRekapDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekapDiagnosaActionPerformed
        // TODO add your handling code here:
        new RekapDiagnosa().show();
        this.dispose();
    }//GEN-LAST:event_btnRekapDiagnosaActionPerformed

    private void btnBasisPengetahuan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasisPengetahuan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBasisPengetahuan2ActionPerformed

    private void btnSparepartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparepartsActionPerformed
        // TODO add your handling code here:
        new DataSpareparts().show();
        this.dispose();
    }//GEN-LAST:event_btnSparepartsActionPerformed

    private void btnAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturanActionPerformed
        // TODO add your handling code here:
        new Aturan(1).show();
        this.dispose();
    }//GEN-LAST:event_btnAturanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAturan;
    private javax.swing.JButton btnBasisPengetahuan;
    private javax.swing.JButton btnBasisPengetahuan2;
    private javax.swing.JButton btnCiriKerusakan;
    private javax.swing.JButton btnKerusakan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRekapDiagnosa;
    private javax.swing.JButton btnSpareparts;
    private javax.swing.JLabel imgBasisPengetahuan;
    private javax.swing.JLabel imgKerusakan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
