/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ZULFA
 */

import java.io.InputStream;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class Konsultasi extends javax.swing.JFrame {

    /**
     * Creates new form Konsultasi
     */
    ArrayList<String> hasil = new ArrayList<>();
    ArrayList<String> dataKerusakan = new ArrayList<>();
    ArrayList<String> kodeCiriKerusakan = new ArrayList<>();
    ArrayList<String> pertanyaanKonsultasi = new ArrayList<>();
    ArrayList<String> resultSolusiKerusakan = new ArrayList<>();
    ArrayList<String> resultCiriKodeKerusakan = new ArrayList<>();
    String akhir = null;
    public Statement st;
    public ResultSet rsp,rs = null;
    String nama = "";
    String resultFinalKodeKerusakan = "";
    Connection cn = database.kerusakandb.configDB();
    
    public Konsultasi() {
        initComponents();
        btnSelanjutnya.setEnabled(false);
        btnBatal.setEnabled(false);
        btnTidak.setEnabled(false);
        btnYa.setEnabled(false);
        btnHasil.setEnabled(false);
        txtKodeCiriKerusakan.setEnabled(false);
        txtJawaban.setEnabled(false);
        txtPertanyaan.setEnabled(false);
        try{
        st = cn.createStatement();
        rsp = st.executeQuery("SELECT * FROM kerusakan");
        while(rsp.next()){
            String namaKerusakan = rsp.getString("nama_kerusakan");
            String solusiKerusakan = rsp.getString("solusi_kerusakan");
            dataKerusakan.add(namaKerusakan);
            resultSolusiKerusakan.add(solusiKerusakan);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnTidak = new javax.swing.JButton();
        btnHasil = new javax.swing.JButton();
        btnSelanjutnya = new javax.swing.JButton();
        btnYa = new javax.swing.JButton();
        btnMulaiDiagnosa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPertanyaan = new javax.swing.JTextArea();
        txtJawaban = new javax.swing.JTextField();
        txtKodeCiriKerusakan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 242, 246));

        jPanel4.setBackground(new java.awt.Color(237, 235, 230));

        btnBatal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnTidak.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnTidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnTidak.setText("tidak");
        btnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTidakActionPerformed(evt);
            }
        });

        btnHasil.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        btnHasil.setText("Lihat Hasil");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        btnSelanjutnya.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSelanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btnSelanjutnya.setText("Selanjutnya");
        btnSelanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelanjutnyaActionPerformed(evt);
            }
        });

        btnYa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnYa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yes.png"))); // NOI18N
        btnYa.setText("ya");
        btnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYaActionPerformed(evt);
            }
        });

        btnMulaiDiagnosa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMulaiDiagnosa.setText("Mulai Diagnosa");
        btnMulaiDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiDiagnosaActionPerformed(evt);
            }
        });

        txtPertanyaan.setColumns(20);
        txtPertanyaan.setRows(5);
        jScrollPane1.setViewportView(txtPertanyaan);

        txtKodeCiriKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeCiriKerusakanActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(55, 58, 58));
        jLabel1.setForeground(new java.awt.Color(55, 58, 58));
        jLabel1.setText("Nama");

        jPanel3.setBackground(new java.awt.Color(237, 235, 230));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnYa)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelanjutnya)
                                .addGap(65, 65, 65)
                                .addComponent(btnHasil))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtKodeCiriKerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(243, 243, 243))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(btnMulaiDiagnosa))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(btnBatal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTidak)
                        .addGap(226, 226, 226))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal)
                    .addComponent(txtKodeCiriKerusakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMulaiDiagnosa)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btnTidak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHasil)
                    .addComponent(btnSelanjutnya)
                    .addComponent(btnYa))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Interview.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void awalPertanyaan(){
        try{
         rs.first();
         txtKodeCiriKerusakan.setText(rs.getString(2));
         txtPertanyaan.setText( "Apakah " + rs.getString(3) + "?");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
     public void lanjutPertanyaan(){
        try{
         rs.next();
         txtKodeCiriKerusakan.setText(rs.getString(2));
         txtPertanyaan.setText("Apakah " + rs.getString(3) + "?");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }
    
     public void akhirPertanyaan(){
        try{
         rs.last();
         akhir = rs.getString(2);
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    } 
     
    private void btnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYaActionPerformed
        // TODO add your handling code here:
        txtJawaban.setText("ya");
    }//GEN-LAST:event_btnYaActionPerformed

    private void btnSelanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelanjutnyaActionPerformed
        // TODO add your handling code here:
        try{
            if(txtKodeCiriKerusakan.getText().equalsIgnoreCase(akhir)){
                 pertanyaanKonsultasi.add(txtPertanyaan.getText());
                 kodeCiriKerusakan.add(rs.getString(2));
                JOptionPane.showMessageDialog(null, "pertanyaan Selesai !! Silahkan tekan tombol DIAGNOSA");
            }else{
                if(txtJawaban.getText().equalsIgnoreCase("ya")){
                    pertanyaanKonsultasi.add(txtPertanyaan.getText());
                    kodeCiriKerusakan.add(rs.getString(2));
                }
                txtJawaban.setText("");
                lanjutPertanyaan();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnSelanjutnyaActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        if(!kodeCiriKerusakan.isEmpty() || !pertanyaanKonsultasi.isEmpty()){
            kodeCiriKerusakan.clear();
            pertanyaanKonsultasi.clear();
        }
        txtPertanyaan.setText("");
        txtKodeCiriKerusakan.setText("");
        txtNama.setText("");
        btnHasil.setEnabled(false);
        btnSelanjutnya.setEnabled(false);
        btnBatal.setEnabled(false);
        btnTidak.setEnabled(false);
        btnYa.setEnabled(false);
        txtKodeCiriKerusakan.setEnabled(false);
        txtJawaban.setEnabled(false);
        txtPertanyaan.setEnabled(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
            // TODO add your handling code here:
        try {
            String resultHasilDiagnosa = "";
            if(txtNama.getText().equals("")){
                JOptionPane.showMessageDialog(null, "ISI FORM NAMA TERLEBIH DAHULU");
            }else if(kodeCiriKerusakan.isEmpty()){
                JOptionPane.showMessageDialog(null, "Anda Belum menjawab pertanyaan satupun");
            }else if(kodeCiriKerusakan.contains("CK001") || kodeCiriKerusakan.contains("CK002") || kodeCiriKerusakan.contains("CK003")){
                resultHasilDiagnosa = "Kemungkinan Vespa anda Mengalami kerusakan '" + dataKerusakan.get(0) + "'";
                nama = txtNama.getText();
                showResultDiagnosa(resultHasilDiagnosa, nama);
            }else if(kodeCiriKerusakan.contains("CK004") || kodeCiriKerusakan.contains("CK005") || kodeCiriKerusakan.contains("CK006")){
                resultHasilDiagnosa = "Kemungkinan Vespa anda Mengalami kerusakan '" + dataKerusakan.get(1) + "'";
                nama = txtNama.getText();
                showResultDiagnosa(resultHasilDiagnosa, nama);
            }
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHasilActionPerformed

    public void showResultDiagnosa(String resultDiagnosa,String nama ){
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO konsultasi (nama,pertanyaan_konsultasi,hasil_konsultasi) VALUES (?,?,?)");
                String pertanyaanKonsul = pertanyaanKonsultasi.toString();
                pst.setString(1, nama);
                pst.setString(2, pertanyaanKonsul.substring(1, pertanyaanKonsul.length() - 1));
                pst.setString(3, resultDiagnosa);
                pst.executeUpdate();
                HasilKonsultasi hasil = new HasilKonsultasi(resultDiagnosa);
                hasil.setVisible(true);
                this.dispose();;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void btnMulaiDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiDiagnosaActionPerformed
        // TODO add your handling code here:
        txtKodeCiriKerusakan.setText("");
        txtPertanyaan.setText("");
        txtJawaban.setText("");
        btnSelanjutnya.setEnabled(true);
        btnYa.setEnabled(true);
        btnTidak.setEnabled(true);
        btnBatal.setEnabled(true);
        btnHasil.setEnabled(true);
        txtKodeCiriKerusakan.setEnabled(true);
        txtNama.setEnabled(true);
        txtJawaban.setEnabled(true);
        txtPertanyaan.setEnabled(true);
        txtKodeCiriKerusakan.setEditable(false);
        txtPertanyaan.setEditable(false);
        txtJawaban.setEditable(false);
        akhirPertanyaan();
        awalPertanyaan();
    }//GEN-LAST:event_btnMulaiDiagnosaActionPerformed

    private void btnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTidakActionPerformed
        // TODO add your handling code here:
        txtJawaban.setText("tidak");
    }//GEN-LAST:event_btnTidakActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          try{
            st = cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("SELECT * FROM ciri_kerusakan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtKodeCiriKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeCiriKerusakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeCiriKerusakanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konsultasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHasil;
    private javax.swing.JButton btnMulaiDiagnosa;
    private javax.swing.JButton btnSelanjutnya;
    private javax.swing.JButton btnTidak;
    private javax.swing.JButton btnYa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtKodeCiriKerusakan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextArea txtPertanyaan;
    // End of variables declaration//GEN-END:variables
}
